### ISSUE TITLE
Please request this repo

### ISSUE THREAD

**Issue by lil5** [matrix-org/gomatrix#102]
Please set the gomatrix repository to archived, or at least add a banner to the readme stating that the package is no longer maintained. 
Cherry on top is to add a link to the GoLang sdk that is maintained. 

github.com/matrix-org/gomatrix

Please remove it from the list of “stable” SDK on matrix.org/ecosystem/sdks/ stable is _not_ synonymous to discontinued.

https://fosstodon.org/@lil5/111940191501771658

**Comment by bluesomewhere** [comment]
Thank you for bringing this to our attention! It's been marked as obsolete on matrix.org/ecosystem/sdks/ and we'll be archiving this repo.
