### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by babolivier** [matrix-org/gomatrix#59]
Currently the CI uses Go 1.8, which isn't supported by some linters anymore, and also makes some calls to Go's tool suite which aren't supported anymore.
This looks like a trivial thing to do, just needs to be done.

**Comment by babolivier** [comment]
According to https://github.com/alecthomas/gometalinter/issues/590, gometalinter is being deprecated and needs to be replaced with [golangci-lint](https://github.com/golangci/golangci-lint).

**Comment by ptman** [comment]
this is probably fixed now

**Comment by Kegsay** [comment]
It is.
