### ISSUE TITLE
Project State / Roadmap

### ISSUE THREAD

**Issue by steirico** [matrix-org/gomatrix#67]
Hi there,

what's the current state of this project? Do you have a meaningful roadmap? Versioning and tags related to the specs?

Since the godocs refer to Client Server API r0.2.0, I'm very reluctant to use this lib for a new project. Instead, I'm seriously thinking about generating an API client based on the provided swagger definitions and [go-swagger](https://github.com/go-swagger/go-swagger).

**Comment by ppwfx** [comment]
hi @steirico, I'm in a similar situation.. how did you decide to move on?

**Comment by steirico** [comment]
hi @ppwfx , I decided to go for the go-swagger road.

**Comment by Kegsay** [comment]
The roadmap continues to be https://github.com/matrix-org/gomatrix/issues/15 

Whilst it would be nice to have this project become as fully fledged as the JS SDK, it will always be playing catchup. Work on [Dendrite](https://github.com/matrix-org/dendrite) is progressing with speed, which is also Go based, so it's likely that gomatrix will benefit from some of that work later down the line.
